language: node_js
node_js:
# use .nvmrc one
before_script:
  - npm install -g bower grunt-cli
services:
  - mongodb
  - redis-server
env:
  global:
    - MONGO_HOST=localhost
    - REDIS_HOST=localhost
